services:
  auth-api:
    container_name: "auth-api-e2e"
    environment:
      - NODE_ENV=${NODE_ENV}
    env_file:
      - .env
    build:
      context: .
      target: "test-e2e"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./key:/usr/keys/key
      - ./key.pub:/usr/keys/key.pub
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - auth-e2e-network

  postgres: 
    container_name: "auth-postgres-e2e"
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: "${POSTGRES_DATABASE}"
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    networks:
      - auth-e2e-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
networks:
  auth-e2e-network:
    name: "auth-e2e-network"

volumes:
  auth-postgres-data: