services:
  auth-api:
    container_name: "auth-api"
    environment:
      - NODE_ENV=${NODE_ENV}
    env_file:
      - .env
    build:
      context: .
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./key:/usr/keys/key
      - ./key.pub:/usr/keys/key.pub
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    networks:
      - auth-network

  postgres: 
    container_name: "auth-postgres"
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: "${POSTGRES_DATABASE}"
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    networks:
      - auth-network
  
  redis:
    image: redis
    container_name: "auth-redis"
    networks:
      - auth-network
  
networks:
  auth-network:
    name: "auth-network"

volumes:
  auth-postgres-data: